# Generated by Django 5.0.4 on 2024-05-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_location_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='sales_nb',
        ),
        migrations.AddField(
            model_name='offer',
            name='sales_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
