# Generated by Django 5.0.4 on 2024-05-30 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_offer_sales_nb_offer_sales_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='sales_count',
        ),
    ]
