# Generated by Django 5.0.4 on 2024-05-30 19:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_offer_sales_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et horaire de début'),
        ),
    ]
