# Generated by Django 5.0.4 on 2024-05-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutjo',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
