# Generated by Django 5.0.4 on 2024-05-30 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_aboutjo_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutjo',
            name='active',
        ),
    ]
