# Generated by Django 5.0.4 on 2024-05-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_order_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_id',
            new_name='payment_key',
        ),
        migrations.AddField(
            model_name='order',
            name='QR_code',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
