# Generated by Django 5.0.4 on 2024-05-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_payment_id_order_payment_key_order_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='QR_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
