# Generated by Django 5.0.4 on 2024-05-30 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_order_items_number_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items_number',
        ),
    ]
